import Foundation
import MetalKit
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers
import CryptoKit

private struct OceanUniforms { var viewport=SIMD4<Float>(1,2.12,0,0); var boat=SIMD4<Float>.zero; var movement=SIMD4<Float>(0,-1,0,0); var color=SIMD4<Float>(0.006,0.22,0.76,0); var optics=SIMD4<Float>(0,0.18,0.6,48) }
private struct OutputRegion { let x:Int; let y:Int; let width:Int; let height:Int }
private enum Failure: Error { case check(String) }
@main struct FastMaterialRender {
    static func sha(_ d:Data)->String { SHA256.hash(data:d).map { String(format:"%02x",$0) }.joined() }
    static func arg(_ n:String)->String? { let a=CommandLine.arguments; guard let i=a.firstIndex(of:n),i+1<a.count else{return nil}; return a[i+1] }
    private static func parseRegion(_ raw:String?,_ width:Int,_ height:Int) throws -> OutputRegion {
        guard let raw else { return OutputRegion(x:0,y:0,width:width,height:height) }
        let p=raw.split(separator:",",omittingEmptySubsequences:false)
        guard p.count==4,let x=Int(p[0]),let y=Int(p[1]),let w=Int(p[2]),let h=Int(p[3]),x>=0,y>=0,w>0,h>0,x<=width-w,y<=height-h else { throw Failure.check("region x,y,w,h") }
        return OutputRegion(x:x,y:y,width:w,height:h)
    }
    static func main(){ do { try run() } catch { fputs("FAIL \(error)\n",stderr); exit(1) } }
    static func run() throws {
        let path=CommandLine.arguments.contains("--path"), progressive=CommandLine.arguments.contains("--progressive"), softLights=CommandLine.arguments.contains("--soft-lights"), softFloor=CommandLine.arguments.contains("--soft-floor"), cubic=CommandLine.arguments.contains("--cubic"), noSkip=path && (CommandLine.arguments.contains("--no-skip") || cubic), aov=arg("--aov"), frame=Int(arg("--frame") ?? "0") ?? 0, width=Int(arg("--width") ?? "600") ?? 600, spp=Int(arg("--spp") ?? "16") ?? 16, seed=Int(arg("--seed") ?? "719") ?? 719
        guard [0,12,24,36,47].contains(frame),width>0,(1...128).contains(spp),aov == nil || ["normal","depth","thickness","source"].contains(aov!),(path || aov == nil),(path || !cubic),(!progressive || (path && aov == nil)),(!softLights || path),(!softFloor || path) else { throw Failure.check("frame/width/spp/aov/progressive") }; let height=Int((Double(width)*2.12).rounded()), region=try parseRegion(arg("--region"),width,height), label=arg("--label") ?? (path ? "path-spp\(spp)-seed\(seed)\(cubic ? "-cubic" : "")\(noSkip ? "-no-skip" : "")\(progressive ? "-progressive" : "")\(softLights ? "-soft-lights" : "")\(softFloor ? "-soft-floor" : "")\(aov.map { "-aov\($0)" } ?? "")" : "candidate"), name=String(format:"%03d",frame), base=URL(fileURLWithPath:".build-cache/fast-material/\(name)"), folder=base.appendingPathComponent("\(label)-\(width)"); try FileManager.default.createDirectory(at:folder,withIntermediateDirectories:true)
        let fieldURL=base.appendingPathComponent("field.f16"),boundsURL=base.appendingPathComponent("bounds.f16"),stateURL=URL(fileURLWithPath:".build-cache/material-motion/\(name)/state.json"),appURL=URL(fileURLWithPath:"SmallWave/Rendering/LiquidShaders.metal"),fastURL=URL(fileURLWithPath:"Studies/FastMaterial.metal"),stochasticURL=URL(fileURLWithPath:"Studies/StochasticMaterial.metal"),harness=try Data(contentsOf:URL(fileURLWithPath:#filePath)),executable=try Data(contentsOf:URL(fileURLWithPath:CommandLine.arguments[0]))
        guard FileManager.default.fileExists(atPath:fieldURL.path),FileManager.default.fileExists(atPath:fastURL.path),!path || (FileManager.default.fileExists(atPath:stochasticURL.path) && FileManager.default.fileExists(atPath:boundsURL.path)) else { throw Failure.check("required shader, bounds, or field unavailable; GPU not run") }
        let field=try Data(contentsOf:fieldURL),boundsData=path ? try Data(contentsOf:boundsURL):nil,stateData=try Data(contentsOf:stateURL),appData=try Data(contentsOf:appURL),fastData=try Data(contentsOf:fastURL),stochasticData=path ? try Data(contentsOf:stochasticURL):nil
        guard let app=String(data:appData,encoding:.utf8),let fast=String(data:fastData,encoding:.utf8),let stochastic=stochasticData.flatMap({String(data:$0,encoding:.utf8)}) ?? (path ? nil : "") else { throw Failure.check("shader UTF-8") }; let source=app+"\n"+(cubic ? "#define FAST_CUBIC_FIELD 1\n" : "")+fast+(path ? "\n"+stochastic : "")
        guard field.count==256*544*48*2 else { throw Failure.check("field bytes") }; for i in stride(from:0,to:field.count,by:2) { let bits=UInt16(field[i])|UInt16(field[i+1])<<8; guard Float(Float16(bitPattern:bits)).isFinite else { throw Failure.check("nonfinite Float16") } }; if let boundsData { guard boundsData.count==64*136*12*4 else { throw Failure.check("bounds bytes") }; for i in stride(from:0,to:boundsData.count,by:4) { let lo=Float(Float16(bitPattern:UInt16(boundsData[i])|UInt16(boundsData[i+1])<<8)),hi=Float(Float16(bitPattern:UInt16(boundsData[i+2])|UInt16(boundsData[i+3])<<8)); guard lo.isFinite,hi.isFinite,lo<=hi else { throw Failure.check("invalid bounds") } } }; try Data(source.utf8).write(to:folder.appendingPathComponent("compiled-source.metal"))
        guard let state=try JSONSerialization.jsonObject(with:stateData) as? [String:Any],let boat=state["boat"] as? [Double],boat.count==4,let energy=state["energy"] as? Double else { throw Failure.check("state boat/energy") }; var u=OceanUniforms(); u.boat=SIMD4(Float(boat[0]),Float(boat[1]),Float(boat[2]),Float(boat[3])); u.movement.w=Float(energy); if path { u.color.w=Float((softLights ? 1:0)+(softFloor ? 2:0)); u.optics.x=Float(spp); u.viewport.z=Float(seed); u.optics.z=noSkip ? 0:1; u.optics.w=aov == "normal" ? -1 : (aov == "depth" ? -2 : (aov == "thickness" ? -3 : (aov == "source" ? -4 : 0))) }
        guard MemoryLayout<OceanUniforms>.stride==80,let device=MTLCreateSystemDefaultDevice(),let queue=device.makeCommandQueue() else { throw Failure.check("Metal") }
        let library=try device.makeLibrary(source:source,options:nil),fragmentName=path ? "stochasticToyFragment":"fastToyFragment"
        let displayDescriptor=MTLRenderPipelineDescriptor(); displayDescriptor.vertexFunction=library.makeFunction(name:"screenVertex"); displayDescriptor.fragmentFunction=library.makeFunction(name:fragmentName); displayDescriptor.colorAttachments[0].pixelFormat = .bgra8Unorm; let pipeline=try device.makeRenderPipelineState(descriptor:displayDescriptor)
        var accumulationPipeline:MTLRenderPipelineState?=nil,resolvePipeline:MTLRenderPipelineState?=nil
        if progressive { let accumulationDescriptor=MTLRenderPipelineDescriptor(); accumulationDescriptor.vertexFunction=library.makeFunction(name:"screenVertex"); accumulationDescriptor.fragmentFunction=library.makeFunction(name:"stochasticToyFragment"); accumulationDescriptor.colorAttachments[0].pixelFormat = .rgba16Float; accumulationDescriptor.colorAttachments[0].isBlendingEnabled=true; accumulationDescriptor.colorAttachments[0].rgbBlendOperation = .add; accumulationDescriptor.colorAttachments[0].alphaBlendOperation = .add; accumulationDescriptor.colorAttachments[0].sourceRGBBlendFactor = .one; accumulationDescriptor.colorAttachments[0].destinationRGBBlendFactor = .one; accumulationDescriptor.colorAttachments[0].sourceAlphaBlendFactor = .one; accumulationDescriptor.colorAttachments[0].destinationAlphaBlendFactor = .one; accumulationPipeline=try device.makeRenderPipelineState(descriptor:accumulationDescriptor); let resolveDescriptor=MTLRenderPipelineDescriptor(); resolveDescriptor.vertexFunction=library.makeFunction(name:"screenVertex"); resolveDescriptor.fragmentFunction=library.makeFunction(name:"stochasticResolveFragment"); resolveDescriptor.colorAttachments[0].pixelFormat = .bgra8Unorm; resolvePipeline=try device.makeRenderPipelineState(descriptor:resolveDescriptor) }
        let vd=MTLTextureDescriptor(); vd.textureType = .type3D; vd.pixelFormat = .r16Float; vd.width=256; vd.height=544; vd.depth=48; vd.storageMode = .shared; vd.usage = .shaderRead; guard let volume=device.makeTexture(descriptor:vd) else { throw Failure.check("volume") }; field.withUnsafeBytes { volume.replace(region:MTLRegionMake3D(0,0,0,256,544,48),mipmapLevel:0,slice:0,withBytes:$0.baseAddress!,bytesPerRow:512,bytesPerImage:256*544*2) }
        var boundsTexture:MTLTexture?; if let boundsData { let bd=MTLTextureDescriptor(); bd.textureType = .type3D; bd.pixelFormat = .rg16Float; bd.width=64; bd.height=136; bd.depth=12; bd.storageMode = .shared; bd.usage = .shaderRead; guard let texture=device.makeTexture(descriptor:bd) else { throw Failure.check("bounds texture") }; boundsData.withUnsafeBytes { texture.replace(region:MTLRegionMake3D(0,0,0,64,136,12),mipmapLevel:0,slice:0,withBytes:$0.baseAddress!,bytesPerRow:64*4,bytesPerImage:64*136*4) }; boundsTexture=texture }
        let stochasticHash:Any=stochasticData.map(sha) ?? NSNull(),boundsHash:Any=boundsData.map(sha) ?? NSNull()
        func writeFailure(_ phase:String,_ samplePass:Int,_ tile:Int,_ gpuError:String) { let report:[String:Any]=["completedAt":ISO8601DateFormatter().string(from:Date()),"device":device.name,"phase":phase,"samplePass":samplePass,"tile":tile,"gpuError":gpuError,"compiledSourceSHA256":sha(Data(source.utf8)),"inputs":["fieldSHA256":sha(field),"boundsSHA256":boundsHash,"stateSHA256":sha(stateData),"appShaderSHA256":sha(appData),"fastShaderSHA256":sha(fastData),"stochasticShaderSHA256":stochasticHash]]; try? JSONSerialization.data(withJSONObject:report,options:[.prettyPrinted,.sortedKeys]).write(to:folder.appendingPathComponent("failure.json")) }
        func finish(_ command:MTLCommandBuffer,_ phase:String,_ samplePass:Int,_ tile:Int) throws -> Double? { command.commit(); command.waitUntilCompleted(); if let error=command.error { writeFailure(phase,samplePass,tile,String(describing:error)); throw error }; guard command.status == .completed else { let message="Metal command status \(command.status.rawValue)"; writeFailure(phase,samplePass,tile,message); throw Failure.check("\(message), tile \(tile)") }; return command.gpuEndTime>command.gpuStartTime ? command.gpuEndTime-command.gpuStartTime:nil }
        let td=MTLTextureDescriptor.texture2DDescriptor(pixelFormat:.bgra8Unorm,width:width,height:height,mipmapped:false); td.storageMode = .shared; td.usage = [.renderTarget,.shaderRead]; guard let target=device.makeTexture(descriptor:td) else { throw Failure.check("target") }; let tileRows=cubic ? 4:64,tiles=Int(ceil(Double(region.height)/Double(tileRows))); var gpu=0.0,available=true
        func drawTiles(_ texture:MTLTexture,_ renderPipeline:MTLRenderPipelineState,_ samplePass:Int,_ uniform:inout OceanUniforms,_ phase:String) throws { for tile in 0..<tiles { let y=region.y+tile*tileRows,h=min(tileRows,region.y+region.height-y); guard let command=queue.makeCommandBuffer() else { throw Failure.check("command") }; let pass=MTLRenderPassDescriptor(); pass.colorAttachments[0].texture=texture; pass.colorAttachments[0].loadAction=(samplePass==0 && tile==0) ? .clear:.load; pass.colorAttachments[0].clearColor=MTLClearColorMake(0,0,0,progressive ? 0:1); pass.colorAttachments[0].storeAction = .store; guard let encoder=command.makeRenderCommandEncoder(descriptor:pass) else { throw Failure.check("encoder") }; encoder.setRenderPipelineState(renderPipeline); encoder.setScissorRect(MTLScissorRect(x:region.x,y:y,width:region.width,height:h)); encoder.setFragmentTexture(volume,index:0); if let boundsTexture { encoder.setFragmentTexture(boundsTexture,index:1) }; encoder.setFragmentBytes(&uniform,length:80,index:0); encoder.drawPrimitives(type:.triangle,vertexStart:0,vertexCount:6); encoder.endEncoding(); if let seconds=try finish(command,phase,samplePass,tile) { gpu+=seconds } else { available=false } } }
        if progressive { guard let accumulationPipeline,let resolvePipeline else { throw Failure.check("progressive pipelines") }; let accumulationDescriptor=MTLTextureDescriptor.texture2DDescriptor(pixelFormat:.rgba16Float,width:width,height:height,mipmapped:false); accumulationDescriptor.storageMode = .shared; accumulationDescriptor.usage = [.renderTarget,.shaderRead]; guard let accumulation=device.makeTexture(descriptor:accumulationDescriptor) else { throw Failure.check("accumulation") }; for samplePass in 0..<spp { var passUniform=u; passUniform.optics.x=1; passUniform.optics.y = -1/Float(spp); passUniform.viewport.z=Float(seed+samplePass*104729); try drawTiles(accumulation,accumulationPipeline,samplePass,&passUniform,"accumulate") }; guard let command=queue.makeCommandBuffer() else { throw Failure.check("resolve command") }; let pass=MTLRenderPassDescriptor(); pass.colorAttachments[0].texture=target; pass.colorAttachments[0].loadAction = .clear; pass.colorAttachments[0].storeAction = .store; guard let encoder=command.makeRenderCommandEncoder(descriptor:pass) else { throw Failure.check("resolve encoder") }; encoder.setRenderPipelineState(resolvePipeline); encoder.setFragmentTexture(accumulation,index:0); encoder.drawPrimitives(type:.triangle,vertexStart:0,vertexCount:6); encoder.endEncoding(); if let seconds=try finish(command,"resolve",spp,-1) { gpu+=seconds } else { available=false } } else { try drawTiles(target,pipeline,0,&u,"render") }
        var bytes=[UInt8](repeating:0,count:width*height*4); bytes.withUnsafeMutableBytes { target.getBytes($0.baseAddress!,bytesPerRow:width*4,from:MTLRegionMake2D(0,0,width,height),mipmapLevel:0) }; let magenta=stride(from:0,to:bytes.count,by:4).reduce(0){$0+(bytes[$1]>245 && bytes[$1+1]<20 && bytes[$1+2]>245 ? 1:0)}; let image=CGImage(width:width,height:height,bitsPerComponent:8,bitsPerPixel:32,bytesPerRow:width*4,space:CGColorSpace(name:CGColorSpace.sRGB)!,bitmapInfo:CGBitmapInfo.byteOrder32Little.union(CGBitmapInfo(rawValue:CGImageAlphaInfo.premultipliedFirst.rawValue)),provider:CGDataProvider(data:Data(bytes) as CFData)!,decode:nil,shouldInterpolate:false,intent:.defaultIntent)!; let pngURL=folder.appendingPathComponent("frame.png"),sink=CGImageDestinationCreateWithURL(pngURL as CFURL,UTType.png.identifier as CFString,1,nil)!; CGImageDestinationAddImage(sink,image,nil); guard CGImageDestinationFinalize(sink) else { throw Failure.check("PNG") }; let png=try Data(contentsOf:pngURL)
        let report:[String:Any]=["completedAt":ISO8601DateFormatter().string(from:Date()),"device":device.name,"frame":frame,"resolution":[width,height],"region":[region.x,region.y,region.width,region.height],"tileRows":tileRows,"mode":path ? "path":"fast","spp":spp,"actualSamplePassCount":progressive ? spp:1,"seed":seed,"aov":aov ?? NSNull(),"noSkip":noSkip,"cubic":cubic,"progressive":progressive,"softLights":softLights,"softFloor":softFloor,"accumulationFormat":progressive ? "rgba16Float":NSNull(),"gpuSeconds":available ? gpu:NSNull(),"magentaErrors":magenta,"appAdopted":false,"offlineFrozenInput":true,"inputs":["fieldSHA256":sha(field),"boundsSHA256":boundsHash,"stateSHA256":sha(stateData),"appShaderSHA256":sha(appData),"fastShaderSHA256":sha(fastData),"stochasticShaderSHA256":stochasticHash,"compiledSourceSHA256":sha(Data(source.utf8)),"harnessSourceSHA256":sha(harness),"executableSHA256":sha(executable),"pngSHA256":sha(png)]]; try JSONSerialization.data(withJSONObject:report,options:[.prettyPrinted,.sortedKeys]).write(to:folder.appendingPathComponent("render.json")); if magenta>0 { throw Failure.check("magentaErrors \(magenta); PNG and render.json preserved") }; print("PASS frame=\(frame) errors=0")
    }
}
